/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import backEnd.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Work
 */
public class adminUsuarios extends javax.swing.JFrame {
    private AdministradorUsuarios admin = new AdministradorUsuarios(); 
    private Usuario actual;
    /**
     * Creates new form adminUsuarios
     */
    
    public adminUsuarios() {
        initComponents();
        showUsuarios();
    }
    
    public adminUsuarios(Usuario user) {
        initComponents();
        showUsuarios();
        this.setActual(user);
    }
    public Usuario getActual() {
        return actual;
    }

    public void setActual(Usuario actual) {
        this.actual = actual;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int codigo = admin.generarNuevoCodigo(); 
        String nombre = JOptionPane.showInputDialog(this, "Nombre:");
        String contraseña = JOptionPane.showInputDialog(this, "Contraseña:");
        int rol = defRol();
        Usuario temp = new Usuario(codigo,nombre,contraseña,rol); 
        String msj = "Desea ingresar el usuario con las siguientes especificaciones?\nCodigo: "+temp.getCodigo()+"\nNombre: "+temp.getNombre()+"\nContraseña: "+temp.getContraseña()+"\nRol: "+temp.getRol()+"**\n\n**Roles\n1.Vendedor\n2.Admin. Inventario\n3.Director: "; 
        int opc = JOptionPane.showConfirmDialog(this, msj); 
        if (opc == 0) {
            admin.insertar(temp);
            showUsuarios();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); 
        if (row > -1){
            Usuario temp = new Usuario(); 
            String cd = String.valueOf(jTable1.getValueAt(row,0)); 
            temp.setCodigo(Integer.parseInt(cd));
            temp.setNombre((String)jTable1.getValueAt(row, 1));
            temp.setContraseña((String)jTable1.getValueAt(row, 2));
            String rl = String.valueOf(jTable1.getValueAt(row,3));
            temp.setRol(Integer.parseInt(rl));
            temp.setNombre(JOptionPane.showInputDialog(this,"Nuevo Nombre:",temp.getNombre())); 
            temp.setContraseña(JOptionPane.showInputDialog(this,"Nueva Contraseña",temp.getContraseña()));
            temp.setRol(defRol());
            String msj = "Desea ingresar el usuario con las siguientes especificaciones?\nCodigo: "+temp.getCodigo()+"\nNombre: "+temp.getNombre()+"\nContraseña: "+temp.getContraseña()+"\nRol: "+temp.getRol()+"**\n\n**Roles\n1.Vendedor\n2.Admin. Inventario\n3.Director: "; 
            int opc = JOptionPane.showConfirmDialog(this, msj); 
            if (opc == 0) {
                admin.modificar(temp);
                showUsuarios();
                }
            }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); 
        if (row > -1){
            Usuario temp = new Usuario(); 
            String cd = String.valueOf(jTable1.getValueAt(row,0)); 
            temp.setCodigo(Integer.parseInt(cd));
            temp.setNombre((String)jTable1.getValueAt(row, 1));
            temp.setContraseña((String)jTable1.getValueAt(row, 2));
            String rl = String.valueOf(jTable1.getValueAt(row,3));
            temp.setRol(Integer.parseInt(rl));
            admin.eliminar(temp); 
            showUsuarios(); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        menuInicio mi = new menuInicio(getActual()); 
        mi.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    private int defRol() {
        int dr = 0; 
        String[] tipos = new String[] {"1","2","3"};
        String r = (String) JOptionPane.showInputDialog(this, "Rol:\n1.Vendedor\n2.Admin. Inventario\n3.Director", "", JOptionPane.QUESTION_MESSAGE,null,tipos,tipos[0]);
        dr = Integer.parseInt(r); 
        return dr; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUsuarios().setVisible(true);
            }
        });
    }
    public final void showUsuarios(){
        Usuario[] listado = admin.getListado();
        listado = admin.sort(listado);
        int lim = listado.length; 
        Object[][] data = new Object[lim][4];
        for (int i = 0; i<lim; i++) {
            data[i][0] = listado[i].getCodigo();
            data[i][1] = listado[i].getNombre();
            data[i][2] = listado[i].getContraseña();
            data[i][3] = listado[i].getRol();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Codigo", "Nombre", "Contraseña", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
