/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import backEnd.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Work
 */
public class visualizadorJuguetes extends javax.swing.JFrame {
    private AdministradorJuguetes admin = new AdministradorJuguetes(); 
    private Usuario actual; 
    /**
     * Creates new form visualizadorJuguetes
     */
    public visualizadorJuguetes() {
        initComponents();
        showJuguetes();
    }
    
    public visualizadorJuguetes(Usuario user) {
        initComponents();
        showJuguetes(); 
        this.setActual(user);
    }

    public Usuario getActual() {
        return actual;
    }

    public void setActual(Usuario actual) {
        this.actual = actual;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Proovedor", "Marca", "Edad", "Tipo", "Valor", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        menuInicio mi = new menuInicio(); 
        mi.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizadorJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizadorJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizadorJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizadorJuguetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizadorJuguetes().setVisible(true);
            }
        });
    }
    
    public void showJuguetes() {
        Juguete[] listado = admin.getListado();
        int lim = listado.length; 
        Object[][] data = new Object[lim][7];
        for (int i = 0; i<lim; i++) {
            data[i][0] = listado[i].getCodigo();
            data[i][1] = listado[i].getCodProveedor(); 
            data[i][2] = listado[i].getMarca();
            data[i][3] = listado[i].getEdad(); 
            data[i][4] = listado[i].getTipo();
            data[i][5] = listado[i].getValorReal(); 
            data[i][6] = listado[i].getCantidad(); 
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Codigo", "Proovedor", "Marca", "Edad", "Tipo", "Valor", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    private int menosJuguetes(int cod, int ex){
        int c = 0; 
        boolean flag = false; 
        while (!(flag)) {
            try {
                c = Integer.parseInt(JOptionPane.showInputDialog(this,"Cuantos Juguetes de ("+cod+") desea vender?:"));
                if (c<ex){
                    flag = true;
                } else {
                    JOptionPane.showMessageDialog(this,"No existe esa cantidad de Juguetes en el inventario");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Cantidad invalida.");
            }    
        }
        return c; 
    }
    private Juguete retrieve(int row) {
        String cJ = String.valueOf(jTable1.getValueAt(row, 0));
        int codigoJ = Integer.parseInt(cJ); 
        String cP = String.valueOf(jTable1.getValueAt(row, 1));
        int codigoP = Integer.parseInt(cP);
        String marca = (String) jTable1.getValueAt(row, 2);
        String age = String.valueOf(jTable1.getValueAt(row, 3));
        int edad = Integer.parseInt(age);
        String tipo = (String) jTable1.getValueAt(row, 4); 
        String comp = String.valueOf(jTable1.getValueAt(row, 5));
        int complejidad = Integer.parseInt(comp); 
        String vU = String.valueOf(jTable1.getValueAt(row, 6));
        float valU = Float.parseFloat(vU);
        String vA = String.valueOf(jTable1.getValueAt(row, 7));
        float valA = Float.parseFloat(vA); 
        String qant = String.valueOf(jTable1.getValueAt(row, 9));
        int cant = Integer.parseInt(qant);
        Juguete temp = new Juguete(codigoJ,codigoP,marca,edad,tipo,complejidad,valU,valA,cant);
        return temp; 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
